//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amicitia.github.io.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amicitia.github.io.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Version	Date	Tags	Description	Update	Thread
        ///smt3-noshadow	Remove Shadow	SMT3	Krisan Thyme	1	8/05/2020	UI		//Remove Shadow (credit to Krisan Thyme) &lt;br&gt;patch=1,EE,202FBD80,extended,00000000 &lt;br&gt;patch=1,EE,202FBD84,extended,00000000 &lt;br&gt;patch=1,EE,202FBD88,extended,00000000 &lt;br&gt;patch=1,EE,202FBD8C,extended,00000000 &lt;br&gt;patch=1,EE,202FBD90,extended,00000000 &lt;br&gt;patch=1,EE,202FBD94,extended,00000000 &lt;br&gt;patch=1,EE,202FBD98,extended,00000000 &lt;br&gt;patch=1,EE,202FBD9C,extended,00000000 &lt;br&gt;pat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cheats {
            get {
                return ResourceManager.GetString("cheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Date	Tags	Description	Embed	Guide URL	Guide Text
        ///modcompendium	Mod Compendium		TGE, ShrineFox, lipsum	9/30/2020	CPK, CVM, SLUS	Easily create, combine and install multiple mods  for Persona 3, 4, 5, P3P, P4G, P5R,  PQ, PQ2, Catherine Full Body and the Dancing games. 	&lt;b&gt;Update 9/30/2020&lt;/b&gt;: Add P5R Update PKG Creation&lt;br&gt;&lt;b&gt;Update 6/22/2020&lt;/b&gt;: Add P4G PC Support&lt;br&gt;&lt;b&gt;Update 4/12/2020&lt;/b&gt;: Fix P3/4 patching, add HostFS output, add option to sort mods by subfolder	https://i.imgur.com/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guides {
            get {
                return ResourceManager.GetString("guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             &lt;/div&gt;
        ///                        &lt;/div&gt;
        ///                    &lt;/div&gt;
        ///                &lt;/td&gt;
        ///                &lt;td width=&quot;75%&quot;&gt;
        ///                    &lt;div class=&quot;text&quot;&gt;
        ///                        &lt;b&gt;Type&lt;/b&gt;:
        ///                        &lt;select onchange=&quot;navigate()&quot; id=&quot;type&quot; name=&quot;type&quot;&gt;
        ///                            &lt;option value=&quot;All&quot;&gt;All&lt;/option&gt;
        ///                            &lt;option value=&quot;Mod&quot;&gt;Mods&lt;/option&gt;
        ///                            &lt;option value=&quot;Tool&quot;&gt;Tools&lt;/option&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexContent {
            get {
                return ResourceManager.GetString("IndexContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;p style=&quot;font-size: 12px;line-height: 0.9;text-align:right;padding-right:10px;color:#fff;&quot;&gt;
        ///    We are not affiliated, associated, authorized, endorsed by, or in any way
        ///    &lt;br&gt;officially connected with ATLUS, SEGA, or any of its subsidiaries or its affiliates.
        ///    &lt;br&gt;The official ATLUS website can be found at &lt;a href=&quot;https://atlus.com&quot;&gt;https://atlus.com&lt;/a&gt;. &quot;Persona&quot;, as well
        ///    &lt;br&gt;as all characters referenced on this page are registere [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexFooter {
            get {
                return ResourceManager.GetString("IndexFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&apos;shortcut icon&apos; href=&apos;favicon.png&apos; type=&apos;image/x-icon&apos; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;Amicitia&lt;/title&gt;
        ///    &lt;link href=&quot;css/index.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;css/waves.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;script src=&quot;https://kit.fontawesome.com/4c3075832a.js&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://amicitia.github.io/js/jquery-3.3.1.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;js/bubbles.js&quot;&gt;&lt;/script&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///&lt;div class=&quot;content&quot;&gt;
        ///    &lt;table id=&quot;wrap&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td width=&quot;25%&quot; style=&quot;vertical-align:top&quot;&gt;
        ///                    &lt;div id=&quot;bloglinks&quot;&gt;
        ///                        &lt;div class&quot;text&quot;&gt;
        ///                            &lt;h3&gt;&lt;i class=&quot;fas fa-newspaper&quot;&gt;&lt;/i&gt; Latest News&lt;/h3&gt;
        ///                            &lt;script src=&quot;js/blogposts.js&quot;&gt;&lt;/script&gt;
        ///                        &lt;br /&gt;&lt;div class=&quot;widget&quot;&gt;.
        /// </summary>
        public static string IndexSidebar {
            get {
                return ResourceManager.GetString("IndexSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Version	Date	Tags	Description	Update	Embed	URL	Text	Icon	Source	Thread	Alt URL	Alt Text	Alt Icon	Guide URL	Guide Text
        ///p4d-jotaro-naoto	Jotaro Costume (Naoto)	P4D	80constant	1	10/11/2020	Player Model, GMD	This is a model import for Naoto that adds a costume with the clothes of Jotaro Kujo from Jojo&apos;s Bizarre Adventure: Stardust Crusaders. Enjoy!		https://www.youtube.com/watch?v=rsOjBhsJf7M	https://drive.google.com/file/d/172-A5KYyS5ywuZK89vAw7tCk4DYkGEhI/view?usp=sharing	Download Mod	fa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mods {
            get {
                return ResourceManager.GetString("mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Version	Date	Tags	Description	Update	Embed	URL	Text	Icon	Source	Thread	Alt URL	Alt Text	Alt Icon	Guide URL	Guide Text
        ///modcompendium	Mod Compendium		TGE, ShrineFox, lipsum	1.5	9/30/2020	CPK, CVM, SLUS	Easily create, combine and install multiple mods  for Persona 3, 4, 5, P3P, P4G, P5R,  PQ, PQ2, Catherine Full Body and the Dancing games. 	&lt;b&gt;Update 9/30/2020&lt;/b&gt;: Add P5R Update PKG Creation&lt;br&gt;&lt;b&gt;Update 6/22/2020&lt;/b&gt;: Add P4G PC Support&lt;br&gt;&lt;b&gt;Update 4/12/2020&lt;/b&gt;: Fix P3/4 patching, add [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
    }
}
