//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amicitia.github.io.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amicitia.github.io.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Date	Tags	Description	Update Text	ThreadID
        ///p3fes-controllableparty	P3FES Controllable Party Members	P3FES	TGE	6/9/2018	PNACH	&quot;This cheat allows you to choose a skill or item on your party member&apos;s turn, similar to in Persona 4 and 5. Known side effects: the protagonist&apos;s fusion skills can be used by everyone on their turns.&quot;	&quot;//Controllable Party Members by TGE&lt;br&gt;&lt;br&gt;patch=1,EE,0029AFC8,word,00000000 // nop check for if battle unit is not mc -&gt; ai&lt;br&gt;patch=1,EE,0020207C,word,00000000  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cheats {
            get {
                return ResourceManager.GetString("cheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Date	Tags	Description	Embed	Guide URL	Guide Text
        ///mod-cpk	Loading Modded files in Persona 5 (PS3)	P5	ShrineFox	3/22/2019	&quot;PS3, Mod, CPK&quot;	This guide walks you through the fundamentals of datamining and replacing files for any region/version of Persona 5 on PS3.	https://i.imgur.com/wYEuTvc.png	https://shrinefox.com/guides/mod-cpk	Loading Modded files in Persona 5 (PS3)
        ///p5-rpcs3-setupguide	Persona 5 RPCS3 Modding Guide 1: Downloads and Setup	P5	Cryptoss	4/19/2019	&quot;CRIPAKGUI, MOD COMPENDIU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string guides {
            get {
                return ResourceManager.GetString("guides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                             &lt;/div&gt;
        ///                        &lt;/div&gt;
        ///                    &lt;/div&gt;
        ///                &lt;/td&gt;
        ///                &lt;td width=&quot;75%&quot; style=&quot;background-color:#0000007F; border-radius:12px;&quot;&gt;
        ///                    &lt;div class=&quot;text&quot;&gt;
        ///                        &lt;b&gt;Type&lt;/b&gt;:
        ///                        &lt;select onchange=&quot;navigate()&quot; id=&quot;type&quot; name=&quot;type&quot;&gt;
        ///                            &lt;option value=&quot;All&quot;&gt;All&lt;/option&gt;
        ///                            &lt;option value=&quot;Mod&quot;&gt;Mods&lt;/option&gt;
        ///                       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexContentHeader {
            get {
                return ResourceManager.GetString("IndexContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;p style=&quot;font-size: 12px;line-height: 0.9;text-align:right;padding-right:10px;color:#fff;&quot;&gt;
        ///    We are NOT affiliated, associated, authorized, endorsed by, or in any way
        ///    &lt;br&gt;officially connected with ATLUS, SEGA, or any of its subsidiaries or its affiliates.
        ///    &lt;br&gt;The official ATLUS website can be found at &lt;a href=&quot;https://atlus.com&quot;&gt;https://atlus.com&lt;/a&gt;.
        ///    &lt;br&gt;ATLUS and SEGA are registered in the U.S. Patent and Trademark Office. ATL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexFooter {
            get {
                return ResourceManager.GetString("IndexFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&apos;shortcut icon&apos; href=&apos;https://amicitia.github.io/images/favicon.png&apos; type=&apos;image/x-icon&apos; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;Amicitia&lt;/title&gt;
        ///    &lt;link href=&quot;css/index.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;link href=&quot;css/waves.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;script src=&quot;https://kit.fontawesome.com/4c3075832a.js&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://amicitia.github.io/js/jquery-3.3.1.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;scri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///&lt;div class=&quot;content&quot;&gt;
        ///    &lt;table id=&quot;wrap&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td width=&quot;25%&quot; style=&quot;vertical-align:top&quot;&gt;
        ///                    &lt;div id=&quot;bloglinks&quot;&gt;
        ///                        &lt;div class&quot;text&quot;&gt;
        ///                            &lt;h3&gt;&lt;i class=&quot;fas fa-newspaper&quot;&gt;&lt;/i&gt; Latest News&lt;/h3&gt;
        ///                            &lt;script src=&quot;js/blogposts.js&quot;&gt;&lt;/script&gt;
        ///                        &lt;br /&gt;&lt;div class=&quot;widget&quot;&gt;.
        /// </summary>
        public static string IndexSidebar {
            get {
                return ResourceManager.GetString("IndexSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Version	Date	Tags	Description	Update	Embed	URL	Text	Icon	Source	Thread	Alt URL	Alt Text	Alt Icon	Guide URL	Guide Text		
        ///p4adachinavi	P4 Adachi Navigator	P4	ShrineFox	1	1/3/2016	&quot;Voice Clips, HUD, UI, Text&quot;	A mod that replaces Teddie&apos;s navigator dialog with Tohru Adachi&apos;s clips from Persona 4 Arena Ultimax.	 	https://www.youtube.com/watch?v=nukx1gSCF4c	https://drive.google.com/open?id=1nrml3H3qFUfZUarUEyvEno-2xqKfofF1	Mod	folder-open	 	 	 	 	 	 	 		
        ///p3adachi	P3FES Playable Adachi	P3FES [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mods {
            get {
                return ResourceManager.GetString("mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID	Title	Game	Author	Version	Date	Tags	Description	Update	Embed	URL	Text	Icon	Source	Thread	Alt URL	Alt Text	Alt Icon	Guide URL	Guide Text
        ///atomencd	AtomEncd	&quot;P3FES, P4, P4D, P4G, P5, P5D, P5R, CFB, PQ, PQ2&quot;	Du&apos;Slingr	1	8/31/2016	&quot;ADX, WAV&quot;	&quot;A GUI interface for creating custom ADX and HCA audio files using &lt;a href=&quot;&quot;https://www.mediafire.com/?9f7d1oydfccf95v&quot;&quot;&gt;CriAtomEncoder&lt;/a&gt;.&quot;		http://i.imgur.com/FpXO5a3.png	https://drive.google.com/open?id=0B1u1OW7aCWULcENyRTNlUUFad1U	Application	file	https://github.co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
    }
}
